const fs = require('node:fs');
const path = require('node:path');

const avatarsDir = path.resolve(__dirname, '../assets/avatars');
const outputFile = path.resolve(__dirname, '../src/data/autoAvatars.ts');

if (!fs.existsSync(avatarsDir)) {
  fs.mkdirSync(avatarsDir, { recursive: true });
}

const supportedExtensions = new Set(['.png', '.jpg', '.jpeg', '.webp', '.svg']);
const files = fs.readdirSync(avatarsDir).filter((file) => {
  const ext = path.extname(file).toLowerCase();
  return supportedExtensions.has(ext);
});

let importsCode = '';
let entriesCode = '';

files.forEach((file, idx) => {
  const ext = path.extname(file);
  const name = path.basename(file, ext);
  const varName = `avatar_${idx}`;
  // Escape special chars for JS string
  const escapedName = JSON.stringify(name);
  const escapedFile = JSON.stringify(`../../assets/avatars/${file}`);

  importsCode += `const ${varName} = new URL(${escapedFile}, import.meta.url).toString();\n`;
  entriesCode += `  ${escapedName}: ${varName},\n`;
});

const content = `// This file is auto-generated by scripts/generate-avatars.js
// Do not edit manually. Place images into assets/avatars/ and run dev or build.

${importsCode}
export const autoAvatars: Record<string, string> = {
${entriesCode}};
`;

fs.writeFileSync(outputFile, content, 'utf-8');
console.log(`[generate-avatars] Generated ${files.length} avatars from assets/avatars/ into src/data/autoAvatars.ts`);
