// This file is auto-generated by scripts/generate-avatars.js
// Do not edit manually. Place images into assets/avatars/ and run dev or build.

const avatar_0 = new URL('../../assets/avatars/강성윤.jpg', import.meta.url).toString();
const avatar_1 = new URL('../../assets/avatars/김고은.jpg', import.meta.url).toString();
const avatar_2 = new URL('../../assets/avatars/김범석.png', import.meta.url).toString();
const avatar_3 = new URL('../../assets/avatars/김준기.jpg', import.meta.url).toString();
const avatar_4 = new URL('../../assets/avatars/김형진.jpg', import.meta.url).toString();
const avatar_5 = new URL('../../assets/avatars/꽉변.png', import.meta.url).toString();
const avatar_6 = new URL('../../assets/avatars/박선주.jpg', import.meta.url).toString();
const avatar_7 = new URL('../../assets/avatars/박유란.jpg', import.meta.url).toString();
const avatar_8 = new URL('../../assets/avatars/서윤희.jpg', import.meta.url).toString();
const avatar_9 = new URL('../../assets/avatars/서호정.jpg', import.meta.url).toString();
const avatar_10 = new URL('../../assets/avatars/손보연.jpg', import.meta.url).toString();
const avatar_11 = new URL('../../assets/avatars/안찬호.jpg', import.meta.url).toString();
const avatar_12 = new URL('../../assets/avatars/왈도쿤.png', import.meta.url).toString();
const avatar_13 = new URL('../../assets/avatars/이민훈.jpg', import.meta.url).toString();
const avatar_14 = new URL('../../assets/avatars/이준영.jpg', import.meta.url).toString();
const avatar_15 = new URL('../../assets/avatars/이현섭.jpg', import.meta.url).toString();
const avatar_16 = new URL('../../assets/avatars/이현중.png', import.meta.url).toString();
const avatar_17 = new URL('../../assets/avatars/임충렬.jpg', import.meta.url).toString();
const avatar_18 = new URL('../../assets/avatars/정동현.jpg', import.meta.url).toString();
const avatar_19 = new URL('../../assets/avatars/정소현.png', import.meta.url).toString();
const avatar_20 = new URL('../../assets/avatars/정승욱.jpg', import.meta.url).toString();
const avatar_21 = new URL('../../assets/avatars/조부연.jpg', import.meta.url).toString();
const avatar_22 = new URL('../../assets/avatars/주누피.png', import.meta.url).toString();
const avatar_23 = new URL('../../assets/avatars/챔루.png', import.meta.url).toString();
const avatar_24 = new URL('../../assets/avatars/최재웅.jpg', import.meta.url).toString();
const avatar_25 = new URL('../../assets/avatars/쿠빈.png', import.meta.url).toString();
const avatar_26 = new URL('../../assets/avatars/파텔아유시.jpg', import.meta.url).toString();

export const autoAvatars: Record<string, string> = {
  강성윤: avatar_0,
  김고은: avatar_1,
  김범석: avatar_2,
  김준기: avatar_3,
  김형진: avatar_4,
  꽉변: avatar_5,
  박선주: avatar_6,
  박유란: avatar_7,
  서윤희: avatar_8,
  서호정: avatar_9,
  손보연: avatar_10,
  안찬호: avatar_11,
  왈도쿤: avatar_12,
  이민훈: avatar_13,
  이준영: avatar_14,
  이현섭: avatar_15,
  이현중: avatar_16,
  임충렬: avatar_17,
  정동현: avatar_18,
  정소현: avatar_19,
  정승욱: avatar_20,
  조부연: avatar_21,
  주누피: avatar_22,
  챔루: avatar_23,
  최재웅: avatar_24,
  쿠빈: avatar_25,
  파텔아유시: avatar_26,
};
